//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADB.Web.App_GlobalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Localisation {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localisation() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ADB.Web.App_GlobalResources.Localisation", typeof(Localisation).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Активный.
        /// </summary>
        public static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Активно-пассивный.
        /// </summary>
        public static string ActivePassive {
            get {
                return ResourceManager.GetString("ActivePassive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата рождения.
        /// </summary>
        public static string BirthDate {
            get {
                return ResourceManager.GetString("BirthDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Место рождения.
        /// </summary>
        public static string BirthPlace {
            get {
                return ResourceManager.GetString("BirthPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Индивидуальный предприниматель.
        /// </summary>
        public static string BusinessmanUserTypeEnum {
            get {
                return ResourceManager.GetString("BusinessmanUserTypeEnum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BYR.
        /// </summary>
        public static string BYR {
            get {
                return ResourceManager.GetString("BYR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Организация.
        /// </summary>
        public static string Company {
            get {
                return ResourceManager.GetString("Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кредит.
        /// </summary>
        public static string CreditContract {
            get {
                return ResourceManager.GetString("CreditContract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип 1.
        /// </summary>
        public static string CreditType1 {
            get {
                return ResourceManager.GetString("CreditType1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип 2.
        /// </summary>
        public static string CreditType2 {
            get {
                return ResourceManager.GetString("CreditType2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Депозит.
        /// </summary>
        public static string DepositContract {
            get {
                return ResourceManager.GetString("DepositContract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип 1.
        /// </summary>
        public static string DepositType1 {
            get {
                return ResourceManager.GetString("DepositType1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип 2.
        /// </summary>
        public static string DepositType2 {
            get {
                return ResourceManager.GetString("DepositType2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Инвалидность.
        /// </summary>
        public static string DisabilityStatus {
            get {
                return ResourceManager.GetString("DisabilityStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В разводе.
        /// </summary>
        public static string Divorsed {
            get {
                return ResourceManager.GetString("Divorsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Эл. почта.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EUR.
        /// </summary>
        public static string EUR {
            get {
                return ResourceManager.GetString("EUR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Первая группа.
        /// </summary>
        public static string FirstLevel {
            get {
                return ResourceManager.GetString("FirstLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Домашний телефон.
        /// </summary>
        public static string HomePhone {
            get {
                return ResourceManager.GetString("HomePhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пенсионер.
        /// </summary>
        public static string IsRetired {
            get {
                return ResourceManager.GetString("IsRetired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кем выдан.
        /// </summary>
        public static string IssuedBy {
            get {
                return ResourceManager.GetString("IssuedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата выдачи.
        /// </summary>
        public static string IssuedDate {
            get {
                return ResourceManager.GetString("IssuedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фамилия.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Семейное положение.
        /// </summary>
        public static string MaritalStatus {
            get {
                return ResourceManager.GetString("MaritalStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Женат\Замужем.
        /// </summary>
        public static string Married {
            get {
                return ResourceManager.GetString("Married", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отчество.
        /// </summary>
        public static string MiddleName {
            get {
                return ResourceManager.GetString("MiddleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мобильный телефон.
        /// </summary>
        public static string MobilePhone {
            get {
                return ResourceManager.GetString("MobilePhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Месячный доход.
        /// </summary>
        public static string MonthlyIncome {
            get {
                return ResourceManager.GetString("MonthlyIncome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Национальность.
        /// </summary>
        public static string Nationality {
            get {
                return ResourceManager.GetString("Nationality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to н/о.
        /// </summary>
        public static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не гражданин.
        /// </summary>
        public static string NonResident {
            get {
                return ResourceManager.GetString("NonResident", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Юридическое лицо.
        /// </summary>
        public static string OrganisationUserTypeEnum {
            get {
                return ResourceManager.GetString("OrganisationUserTypeEnum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пассивный.
        /// </summary>
        public static string Passive {
            get {
                return ResourceManager.GetString("Passive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ид. № паспорта.
        /// </summary>
        public static string PassportId {
            get {
                return ResourceManager.GetString("PassportId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to № паспорта.
        /// </summary>
        public static string PassportNumber {
            get {
                return ResourceManager.GetString("PassportNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Серия паспорта.
        /// </summary>
        public static string PassportSeries {
            get {
                return ResourceManager.GetString("PassportSeries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Физическое лицо.
        /// </summary>
        public static string PersonUserTypeEnum {
            get {
                return ResourceManager.GetString("PersonUserTypeEnum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Должность.
        /// </summary>
        public static string Position {
            get {
                return ResourceManager.GetString("Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Адрес регистрации.
        /// </summary>
        public static string RegistrationAddress {
            get {
                return ResourceManager.GetString("RegistrationAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Адрес проживания.
        /// </summary>
        public static string ResidenceAddress {
            get {
                return ResourceManager.GetString("ResidenceAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Город проживания.
        /// </summary>
        public static string ResidenceCityId {
            get {
                return ResourceManager.GetString("ResidenceCityId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Гражданин.
        /// </summary>
        public static string Resident {
            get {
                return ResourceManager.GetString("Resident", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вторая группа.
        /// </summary>
        public static string SecondLevel {
            get {
                return ResourceManager.GetString("SecondLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не женат\Не замужем.
        /// </summary>
        public static string Single {
            get {
                return ResourceManager.GetString("Single", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Третья группа.
        /// </summary>
        public static string ThirdLevel {
            get {
                return ResourceManager.GetString("ThirdLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USD.
        /// </summary>
        public static string USD {
            get {
                return ResourceManager.GetString("USD", resourceCulture);
            }
        }
    }
}
